# Generated by Django 5.1.4 on 2025-03-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameranumber', models.BigIntegerField()),
                ('latitude', models.CharField(max_length=100)),
                ('logitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='missingcase_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=100)),
                ('childimage', models.FileField(upload_to='')),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('missingdate', models.DateField()),
                ('uploaddate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='childhelpline_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('logitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='myapp.login_table')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='cameranotification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.CharField(max_length=100)),
                ('logitude', models.CharField(max_length=100)),
                ('CAMERANUMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_table')),
                ('MISSINGCASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.missingcase_table')),
            ],
        ),
        migrations.CreateModel(
            name='update_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('MISSINGCASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.missingcase_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='missingcase_table',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='emergencycomplaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('CHILDLINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.childhelpline_table')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
    ]
