# Generated by Django 5.1.4 on 2025-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cameranotification_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameranotification_table',
            name='image',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
